#!/usr/bin/env bash
# Bash script to configure Nginx on Ubuntu and create custom error pages

# Update and upgrade packages
sudo apt update -y
sudo apt upgrade -y

# Install Nginx
sudo apt install nginx -y

# Start Nginx service
sudo service nginx start

# Set the main page content
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Configure Nginx default site
new_string='server_name _;\n\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;\n\n\terror_page 404 \/404.html;'
sudo sed -i "s/server_name _;/${new_string}/" /etc/nginx/sites-available/default

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Enable custom error page in Nginx configuration
sudo sed -i 's/^\t\}$/\t\}\n\n\terror_page 404 \/404.html;/' /etc/nginx/sites-available/default

# Enable the default site configuration
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart

# End of script

