#!/usr/bin/env bash
# script that create the file /var/run/myscript.pid containing its PID

iterator()
{
	rm /var/run/myscript.pid
	exit
}
echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y u no love me?"' SIGINT
	trap 'echo "I hate the  kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done
