#!/usr/bin/env bash
#script Display "best School" 10 times using while loop

iterator=0

while [ $iterator -lt 10 ]
do
	if [ $iterator -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( iterator++ ))
done

