#!/usr/bin/env bash
#bash script that loop from 1 to 10
# displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
iterator=0

while [ $iterator -lt 10 ]
do
	if [ $iterator -eq 3 ]
	then
		echo "bad luck"
	elif [ $iterator -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( iterator++ ))
done
