#!/usr/bin/env bash
#script that display a time of 12 hours and 59 minutes

hours= 0
while [ $hours -le 12 ]
do
	echo "Hour: $hours"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
	done
	(( hour++ ))
done

