#!/usr/bin/bash
# Check if the script is run as root
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this script as root."
    exit 1
fi
if grep -q "127.0.0.2 localhost" /etc/hosts; then
    echo "Hosts file already configured."
else
    echo "127.0.0.2 localhost" >> /etc/hosts
    echo "Hosts file configured to resolve localhost to 127.0.0.2."
fi
if grep -q  "8.8.8.8 facebook.com" /etc/hosts; then
    echo "Hosts file already configured."
else
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi
